version: '{build}'

environment:
  project_name: ExcelMerge

image:
  - Visual Studio 2017

configuration:
  - Release

build:
  verbosity: minimal
  
before_build:
  - ps: nuget restore
  
after_build:
- ps: dir .

artifacts:
- path: ExcelMerge\bin\release\
  name: test

